// Generated by KeyTable.genHeaderFile() and genSourceFile()
#pragma once
#include <QString>

class ActionTypes {

public:

    static QString value1;

    static int value2;

    static QString value3;

    static QString custom;

    static qreal value4;

};
